### ISSUE TITLE
Syntax highlight doesn't support fenced code block

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#98]
Although the parser supports fenced code block, the syntax highlighter seems not.

e.g.

``````
```
# this should not be headered
```
``````

Reported by: colinfang

Original Ticket: [retext/tickets/98](https://sourceforge.net/p/retext/tickets/98)

**Comment by emanuel-th** [comment]
I saw #253 and thought fenced code blocks are not supported by markdown, only by commonmark? The [original markdown page](https://daringfireball.net/projects/markdown/syntax) does not mention it.

Anyway I have a more complex example. A fenced code block within a list.
see [list-code.md](https://github.com/retext-project/retext/files/14314253/list-code.md)
The first has the problem as described in #158. The second renders correctly, but each list item has number one. As the block code is not indented and it starts a new list?

I'm using retext 7.2.3.

If you paste it as comment, Github renders it as intended.

**Comment by mitya57** [comment]
Hi @emanuel-th!

> I saw #253 and thought fenced code blocks are not supported by markdown, only by commonmark? The [original markdown page](https://daringfireball.net/projects/markdown/syntax) does not mention it.

The fenced code blocks are not part of the standard Markdown syntax, however Python-Markdown supports them via the [Fenced Code Blocks](https://python-markdown.github.io/extensions/fenced_code_blocks/) extension. And in ReText, the [Extra extension set](https://python-markdown.github.io/extensions/extra/) (which includes fenced_code) is enabled by default.

> Anyway I have a more complex example. A fenced code block within a list. see [list-code.md](https://github.com/retext-project/retext/files/14314253/list-code.md) The first has the problem as described in #158.

As the documentation of the Fenced Code extension says,

> [!WARNING]  
> Fenced Code Blocks are only supported at the document root level. Therefore, they cannot be nested inside lists or blockquotes. If you need to nest fenced code blocks, you may want to try the third party extension [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) instead.

So, indeed, SuperFences should solve the problem of using the fenced code block in a list. See our [wiki](https://github.com/retext-project/retext/wiki/Markdown-extensions) for details on how to enable extensions.

> The second renders correctly, but each list item has number one. As the block code is not indented and it starts a new list?

Yes, in order for something to be appended to a list item, it needs to be indented with 4 spaces. Otherwise it is not part of the list.

Alternatively, you can use normal code blocks. For that, you need 8 spaces indentation (first 4 for a list item and another 4 for a code block). So, this will render as you expect:

```markdown
1. some bash file

        #!/bin/bash
        echo "Hello World!"

2. second headline
```

**Comment by emanuel-th** [comment]
I don't get superfences to work. I installed the extention with pip3. In python console I can "import pymdownx.superfences" without problems.
I added line to `$HOME/.config/markdown-extensions.txt` and tried `<!-- Required extensions: pymdownx.superfences -->` at the beginning of the document, the rendering is still broken.

Any way to debug this?
strace shows it does not open `$HOME/.config/markdown-extensions.txt`.
It access several files under `$HOME/.local/` where the markdown extensions are installed, superfences.py is not one of them.

**Comment by mitya57** [comment]
There was a bug in interaction between mdx_posmap (used for synchronized scrolling) and superfences in lists.

I fixed it in master branch, commit 8bd8f58e18e7e209da1f5dd94cfcca8a6e616c0b. Any chance you could try the version from master?

**Comment by emanuel-th** [comment]
Tested it, still produces a heading.

**Comment by mitya57** [comment]
Can you paste or attach your Markdown file, please?

**Comment by emanuel-th** [comment]
Same as above.
Also tested with
`<!-- Required extensions: pymdownx.superfences -->`
header.

**Comment by emanuel-th** [comment]
[list-code.md](https://github.com/retext-project/retext/files/14417226/list-code.md)

html files: "We don’t support that file type." Using gist. When pasting html there it adds the empty lines.
https://gist.github.com/emanuel-th/8aa571c5576d2c75e9221cf761a94373

**Comment by mitya57** [comment]
Your input file produces the correct result with ReText version from master branch (e72f17c65b46f7189622aa65550e953768dc23b0):

![Screenshot](https://github.com/retext-project/retext/assets/1381584/75443ac6-b2ad-4f08-b4d9-4ebb58b2c6e6).

I notice that your HTML file has this line:
```html
<meta name="generator" content="ReText 7.2.3">
```

which means you are using an older version. The version from master will identify itself as `ReText 8.1.0 (Git)`.

Anyway, the next stable release will include this fix.

**Comment by mitya57** [comment]
Right, I can reproduce this.

It looks like it depends on the order in which extensions are applied: both `pymdownx.superfences` and `fenced_code` try to provide handler for triple-backtick syntax, and whichever is applied last takes the priority.

To solve this, add the virtual `remove_extra` name to the list of extensions:

    

This way it should work always.

Also, I will try to make the order of extensions deterministic, to handle similar situations better.

**Comment by mitya57** [comment]
Yesterday's pymarkups 4.1.0 release makes the order of extensions deterministic (sorted alphabetically) so, as a consequence, `pymdownx.superfences` now works without the need for `remove_extra`.
